name: build-pipeline

on:
  pull_request:
    branches:
      - main
      - release/v*

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: cd frontend && yarn install
      - name: Build frontend docker image
        shell: bash
        run: |
          make build-frontend-amd64

  build-query-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Build signoz community image
        shell: bash
        run: |
          make build-signoz-community-amd64

  build-ee-query-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Build signoz image
        shell: bash
        run: |
          make build-signoz-amd64
