name: post-release

on:
  release:
    types: [published]

jobs:
  merge-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge back main to develop
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin main develop
          git checkout develop
          git merge main
          git push origin develop
